const products = [
    {
        id: "CPU-1",
        title: "AMD Ryzen™ 7 7800X3D 8-Core, 16-Thread",
        description: "The Dominant Gaming Processor, with AMD 3D V-Cache™ Technology for Even More Game PerformanceWhatever the setting, whatever the resolution, lead your team to victory with this incredible gaming processor. Plus, enjoy the benefits of next-gen AMD 3D V-Cache™ technology for low latency and even more game performance.",
        about1: "Processor with 4.20 GHz clock speed for reliable and fast execution of instructions to ensure maximum convenience and feasibility.",
        about2: "Graphics Frequency: 2200 MHZ.",
        about3: "Maximum Operating Temperature: 89°C.",
        category: "cpus",
        stock: 7,
        price: 449,
        pictureUrl: "../img/products/amd-ryzen-7-7800x3d.webp",
    },
    {
        id: "CPU-2",
        title: "AMD Ryzen™ 9 7950X 16-Core, 32-Thread",
        description: "Processor with 4.20 GHz clock speed for quick and dependable processing of data to ensure maximum productivity, this hexadeca-core (16 Core) processor core efficiently handles data to ensure quicker transfer of information with maximum usability.",
        about1: " Processor with 4.50 GHz clock speed for quick and dependable processing of data to ensure maximum productivity.",
        about2: "Hexadeca-core (16 Core) processor core efficiently handles data to ensure quicker transfer of information with maximum usability.",
        about3: "Processor consumes less power to offer maximum productivity with added usability.",
        category: "cpus",
        stock: 5,
        price: 699,
        pictureUrl: "../img/products/amd-ryzen-9-7950x3d.webp",
    },
    {
        id: "GPU-1",
        title: "ASUS TUF Gaming GeForce RTX™ 4070 OC Edition 12GB",
        description: "TUF is here to last, with the all-new ASUS TUF Gaming NVIDIA GeForce RTX™ 4070 OC Edition 12GB GDDR6X. This gaming graphics card provides you with all the power, stability, and durability you will ever need for your next-gen gaming system. The ASUS TUF Gaming NVIDIA GeForce RTX™ 4070 OC Edition comes fully equipped with a vented exoskeleton, a compact PCB, and Military-grade capacitors for a sturdy, and reliable gaming experience.",
        about1: "Powered by NVIDIA DLSS3, ultra-efficient Ada Lovelace arch, and full ray tracing.",
        about2: "Memory Speed : 21 Gbps.",
        about3: "Recommended PSU : 750W.",
        category: "gpus",
        stock: 10,
        price: 679.99,
        pictureUrl: "../img/products/rtx-4070-tuf-gaming-12gb.webp",
    },
    {
        id: "GPU-2",
        title: "ASUS ProArt GeForce RTX™ 4060 OC Edition 8GB",
        description: "The brand new 40 series ProArt has arrived. With an all-new slim 2.5 slot small form factor design the ASUS ProArt GeForce RTX™ 4060 OC Edition 8GB is now ready for any case and any environment you find yourself in. From 3D rendering to video and photo editing, you'll be sure to have all the power in the smallest package possible.",
        about1: "NVIDIA Ada Lovelace Streaming Multiprocessors: Up to 2x performance and power efficiency.",
        about2: "4th Generation Tensor Cores: Up to 4x performance with DLSS 3 vs. brute-force rendering.",
        about3: "3rd Generation RT Cores: Up to 2x ray tracing performance.",
        category: "gpus",
        stock: 8,
        price: 369.99,
        pictureUrl: "../img/products/rtx-4060-pro-art-8gb.webp",
    },
    {
        id: "STRG-1",
        title: "Samsung 970 EVO Plus SSD 2TB NVMe M.2",
        description: "For intensive workloads on PCs and workstations, the Samsung 970 EVO Plus delivers ultimate performance powered by Samsung's NVMe SSD leadership. It is upgraded to be faster than the 970 EVO. It maximizes the potential of NVMe bandwidth for unbeatable computing that meets the needs of the most demanding tech enthusiasts and professionals. For performance that puts you in command, the 970 EVO Plus combines the next-gen PCIe Gen 3.0 x4 NVMe interface with the latest V-NAND technology to achieve fearless read/write speeds.",
        about1: "Breakthrough Read/Write Speeds: The 970 EVO Plus reaches sequential read/write speeds up to 3,500/3,300 MB/s, up to 53%* faster than the 970 EVO.",
        about2: "Superior Heat Dissipation: Samsung's Dynamic Thermal Guard automatically monitors and maintains optimal operating temperatures to minimize performance drops.",
        about3: "Always Evolving SSD: The 970 EVO Plus is powered by the latest V-NAND technology and firmware optimization, maximizing the potential of NVMe bandwidth.",
        category: "storage",
        stock: 20,
        price: 149.99,
        pictureUrl: "../img/products/samsung-970-evo-nvme-ssd-2tb.webp",
    },
    {
        id: "STRG-2",
        title: "Western Digital WD_BLACK 1TB SN850X NVMe M.2",
        description: "Strap in for breakneck gaming speeds with the WD_BLACK SN850X NVMe™ SSD. Crush load times and slash throttling, lagging, and texture pop-ins for a smooth, fast experience that lets you compete at your absolute peak. With the advanced features of Game Mode 2.0 (Windows only) automatically turned on by the WD_BLACK Dashboard and supporting Microsoft's DirectStorage technology, the WD_BLACK SN850X NVMe SSD delivers top-tier performance to keep you playing, streaming, recording, and dominating the game.",
        about1: "The WD_BLACK Dashboard monitors your drive’s health, controls your RGB style and can automatically detect games to turn on Game Mode 2.0 (Windows only).",
        about2: "Predictive Loading, Overhead Balancing, and Adaptive Thermal Management features come to the SN850X to juice up your gaming performance.",
        about3: "Get the ultimate gaming edge over your competition with insane speeds up to 7,300 MB/s.",
        category: "storage",
        stock: 17,
        price: 84.99,
        pictureUrl: "../img/products/wd-black-sn850x-1tb-nvme-ssd.webp",
    },
    {
        id: "RAM-1",
        title: "Corsair Vengeance RGB DDR5 32GB 6000MHz - Black",
        description: "CORSAIR VENGEANCE RGB DDR5 memory delivers DDR5 performance, higher frequencies, and greater capacities optimized for Intel® motherboards while lighting up your PC with dynamic, individually addressable ten-zone RGB lighting. Tightly screened high-frequency memory chips enable faster processing, rendering, and buffering than ever, with onboard voltage regulation for easy, finely controlled overclocking.",
        about1: "Dynamic Ten-Zone RGB Lighting: Illuminate your system with ten individually addressable, ultra-bright RGB LEDs per module, encased in a panoramic light bar for vivid RGB lighting from any viewing angle.",
        about2: "Custom Intel XMP 3.0 Profiles: Customize and save your own XMP profiles via iCUE to tailor performance by app or task for greater efficiency.",
        about3: "Create and Customize: Choose from dozens of preset lighting profiles, or create your own in iCUE.",
        category: "ram",
        stock: 10,
        price: 109.99,
        pictureUrl: "../img/products/corsair-vengeance-ddr5-rgb-black.webp",
    },
    {
        id: "RAM-2",
        title: "Corsair Vengeance RGB DDR5 64GB 6000MHz - White",
        description: "CORSAIR VENGEANCE RGB DDR5 memory delivers DDR5 performance, higher frequencies, and greater capacities optimized for Intel® motherboards while lighting up your PC with dynamic, individually addressable ten-zone RGB lighting. Tightly screened high-frequency memory chips enable faster processing, rendering, and buffering than ever, with onboard voltage regulation for easy, finely controlled overclocking.",
        about1: "Dynamic Ten-Zone RGB Lighting: Illuminate your system with ten individually addressable, ultra-bright RGB LEDs per module, encased in a panoramic light bar for vivid RGB lighting from any viewing angle.",
        about2: "Custom Intel XMP 3.0 Profiles: Customize and save your own XMP profiles via iCUE to tailor performance by app or task for greater efficiency.",
        about3: "Create and Customize: Choose from dozens of preset lighting profiles, or create your own in iCUE.",
        category: "ram",
        stock: 10,
        price: 219.99,
        pictureUrl: "../img/products/corsair-vengeance-ddr5-rgb-white.webp",
    },
    {
        id: "CASE-1",
        title: "Corsair 4000D Airflow Tempered Glass Mid-Tower",
        description: "The CORSAIR 4000D AIRFLOW is a mid-tower ATX case with easy cable management and exceptional cooling. A steel front panel offers optimal airflow to your components, accompanied by two included 120mm AirGuide fans designed with anti-vortex vanes that enhance cooling. The CORSAIR RapidRoute cable management system makes it effortless to route major cables through a single channel, with 25mm of routing depth.",
        about1: "Combining innovative cable management, concentrated airflow, and proven CORSAIR build quality, the 4000D is a fitting choice for an immaculate high-performance PC.",
        about2: "Maximum PSU Length : 220. Radiator Compatibility : 120mm, 140mm, 240mm, 280mm, 360mm.",
        about3: "Includes two CORSAIR 120mm AirGuide fans, utilizing anti-vortex vanes to concentrate airflow and enhance cooling. Motherboard will fit in our 4000 Series cases without any issue. Mini-ITX, micro-ATX, ATX, and E-ATX form factor motherboards are all supported.",
        category: "cases",
        stock: 8,
        price: 79.99,
        pictureUrl: "../img/products/corsair-4000d-airflow-tempered-glass.webp",
    },
    {
        id: "CASE-2",
        title: "NZXT H6 Flow RGB Tempered Glass Mid-Tower",
        description: "Experience performance with a fresh perspective. The H6 Flow's innovative compact design emphasizes GPU cooling with a strategically angled front corner, so the fans direct air where it's most needed. The panoramic glass proudly showcases the interior, while the dual-chamber layout frees up space for a cleaner look and better cooling performance.",
        about1: "Wraparound glass panels with a seamless edge provides an unobstructed view of the inside to highlight key components.",
        about2: "Compact dual-chamber design improves overall thermal performance and creates a clean, uncrowded aesthetic.",
        about3: "Includes three pre-installed 120mm RGB fans positioned at an ideal angle for optimal out-of-the-box cooling and vibrant RGB lighting.",
        category: "cases",
        stock: 5,
        price: 134.99,
        pictureUrl: "../img/products/nzxt-h6-rgb.webp",
    },
    {
        id: "COOLING-1",
        title: "Corsair iCUE H150i Elite LCD XT Liquid CPU Cooler",
        description: "The CORSAIR iCUE H150i ELITE LCD XT Liquid CPU Cooler delivers powerful, customized cooling for your CPU, with a personalized LCD screen that displays GIFs, images, and system information. CORSAIR AF RGB ELITE PWM fans produce incredible low-noise airflow with speeds up to 2,100 RPM, using AirGuide technology for concentrated cooling to disperse heat along a 360mm radiator.",
        about1: "Premium All-in-One LCD CPU Cooler: Combines powerful, low-noise cooling with a personalized LCD display to accent your system’s aesthetics and track its real-time performance at a glance.",
        about2: "Brilliant IPS LCD Display: Showcase your live CPU temperature, favorite animated GIF, funniest meme, your team’s logo, or any image you like on a custom 2.1” IPS LCD screen with 480x480 resolution, ultra-bright 600cd/m² backlight, 24-bit true colour depth, and over 16.7 million colors.",
        about3: "Pick Your Theme: A diverse library of colorful themes let you view vital system information in bold graphic display styles that suit your system and setup.",
        category: "cooling",
        stock: 5,
        price: 289.99,
        pictureUrl: "../img/products/corsair-icue-h150i-aio.webp",
    },
    {
        id: "COOLING-2",
        title: "PCCOOLER 120mm Case Fan 3 Pack Dark Night Series",
        description: "DN-120 computer fans are compatible with all types of chassis and easy to install. Humanized power supply interface design, two interfaces of small 3PIN on the motherboard and 4PIN for power supply D-type Port. Please do not connect 4PIN and 3PIN at the same time to avoid short circuit!",
        about1: "Fans are surrounded by eight soft silicone cushions that can absorb vibration at high speeds. The maximum noise is only 22.93dBA, which is equivalent to the sound of fallen leaves.",
        about2: "Fans adopt featuring ultra durable fluid dynamic bearings. using a unique loop-type oil supply circuit. It can absorb and conserve lubricating oil. The bearing life can reach more than 40,000 hours.",
        about3: "The air volume of 9 high-pressure fan blades can reach 42.67CFM at a speed of 1200. DN-120 case fans focuse on improving the performance, bringing stable wind pressure and powerful air volume.",
        category: "cooling",
        stock: 15,
        price: 19.99,
        pictureUrl: "../img/products/pccooler-3pack-dark-night-fans.webp",
    },
]

const getProducts = new Promise((resolve) => {
    setTimeout(() => {
        resolve(products);
    }, 3000)
});

export default getProducts;